# Site settings
baseurl: "/courses/data-dh.2015"
url: "http://lincolnmullen.com/courses/data-dh.2016"
source: source
destination: public

# Build settings
plugins: plugins
markdown: pandoc
pandoc:
  extensions:
    - smart
permalink: pretty
lsi: false

# Draft or not?
draft: false

# Course information
title: "Data and Digital History"
course_catalog: 
course_credithours: 3
course_department: Dept. of History and Art History
course_university: George Mason Univ.
course_meetingtime: ""
course_number: ""
course_room: ""
course_semester: "Spring 2016"
course_blog: 
instructor_email: lmullen@gmu.edu
instructor_name: Lincoln Mullen
instructor_office: "Research Hall 457"
instructor_officehours: TBD
instructor_officehours_link: http://lincolnmullen.com/officehours
instructor_website: http://lincolnmullen.com
